In [1]:
import pandas as pd
import numpy as np

In [ ]:
!ls -l

In [2]:
loan_data = pd.read_csv("loan-train.csv")

In [3]:
loan_data

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

## Checking dataset for empty or null values

In [5]:
loan_data.apply(lambda x: sum(x.isnull()),axis=0)

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
loan_data.count()

Loan_ID              614
Gender               601
Married              611
Dependents           599
Education            614
Self_Employed        582
ApplicantIncome      614
CoapplicantIncome    614
LoanAmount           592
Loan_Amount_Term     600
Credit_History       564
Property_Area        614
Loan_Status          614
dtype: int64

In [7]:
loan_data.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
loan_data.isnull().sum()

## Filling all empty or null values with proper values

In [8]:
loan_data['Gender'].value_counts()

Male      489
Female    112
Name: Gender, dtype: int64

In [9]:
loan_data.Gender = loan_data.Gender.fillna('Male')

In [10]:
loan_data.apply(lambda x: sum(x.isnull()),axis=0)

Loan_ID               0
Gender                0
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [11]:
loan_data['Married'].value_counts()

Yes    398
No     213
Name: Married, dtype: int64

In [12]:
loan_data.Married = loan_data.Married.fillna('Yes')

In [13]:
loan_data['Dependents'].value_counts()

0     345
1     102
2     101
3+     51
Name: Dependents, dtype: int64

In [14]:
loan_data.Dependents = loan_data.Dependents.fillna('0')

In [15]:
loan_data['Self_Employed'].value_counts()

No     500
Yes     82
Name: Self_Employed, dtype: int64

In [16]:
loan_data.Self_Employed = loan_data.Self_Employed.fillna('No')

In [17]:
loan_data.LoanAmount

0        NaN
1      128.0
2       66.0
3      120.0
4      141.0
       ...  
609     71.0
610     40.0
611    253.0
612    187.0
613    133.0
Name: LoanAmount, Length: 614, dtype: float64

## Filling loan amount data

In [18]:
loan_data.LoanAmount.min()

9.0

In [19]:
loan_data.LoanAmount.max()

700.0

In [20]:
loan_data.LoanAmount.mean()

146.41216216216216

In [21]:
loan_data.LoanAmount = loan_data.LoanAmount.fillna(loan_data.LoanAmount.mean())

## Working with Loan amount Terms

In [22]:
loan_data['Loan_Amount_Term'].isnull().values.sum()

14

In [23]:
loan_data['Loan_Amount_Term'].value_counts()

360.0    512
180.0     44
480.0     15
300.0     13
84.0       4
240.0      4
120.0      3
36.0       2
60.0       2
12.0       1
Name: Loan_Amount_Term, dtype: int64

In [24]:
loan_data.Loan_Amount_Term = loan_data.Loan_Amount_Term.fillna(360.0)

## Working with credit History 

In [25]:
loan_data['Credit_History'].value_counts()

1.0    475
0.0     89
Name: Credit_History, dtype: int64

In [26]:
loan_data.Credit_History = loan_data.Credit_History.fillna(1.0)

## Rechecking the dataset for missing values

In [27]:
loan_data.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

# Now we have good data ready for machine learning

In [28]:
loan_data.sample(10)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
602  LP002953    Male     Yes         3+      Graduate            No   
476  LP002529    Male     Yes          2      Graduate            No   
212  LP001713    Male     Yes          1      Graduate           Yes   
175  LP001606    Male     Yes          0      Graduate            No   
410  LP002318  Female      No          1  Not Graduate           Yes   
547  LP002772    Male      No          0      Graduate            No   
511  LP002640    Male     Yes          1      Graduate            No   
370  LP002194  Female      No          0      Graduate           Yes   
2    LP001005    Male     Yes          0      Graduate           Yes   
181  LP001634    Male      No          0      Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
602             5703                0.0       128.0             360.0   
476             6700             1750.0       230.0             300.0   
212             7787                0.0       240.0             360.0   
175             3497             1964.0       116.0             360.0   
410             3867                0.0        62.0             360.0   
547             2526             1783.0       145.0             360.0   
511             6065             2004.0       250.0             360.0   
370            15759                0.0        55.0             360.0   
2               3000                0.0        66.0             360.0   
181             1916             5063.0        67.0             360.0   

     Credit_History Property_Area Loan_Status  
602             1.0         Urban           Y  
476             1.0     Semiurban           Y  
212             1.0         Urban           Y  
175             1.0         Rural           Y  
410             1.0     Semiurban           N  
547             1.0         Rural           Y  
511             1.0     Semiurban           Y  
370             1.0     Semiurban           Y  
2               1.0         Urban           Y  
181             1.0         Rural           N

In [29]:
loan_data.shape

(614, 13)

In [30]:
loan_data.head(1)

Loan_ID Gender Married Dependents Education Self_Employed  \
0  LP001002   Male      No          0  Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y

# Feature Engineering

In [31]:
for i in [loan_data]:
    loan_data['TotalIncome'] = loan_data['ApplicantIncome'] + loan_data['CoapplicantIncome']

In [32]:
loan_data.shape

(614, 14)

In [33]:
loan_data.sample(10)

Loan_ID Gender Married Dependents     Education Self_Employed  \
182  LP001636   Male     Yes          0      Graduate            No   
379  LP002225   Male     Yes          2      Graduate            No   
83   LP001273   Male     Yes          0      Graduate            No   
452  LP002448   Male     Yes          0      Graduate            No   
340  LP002115   Male     Yes         3+  Not Graduate            No   
216  LP001722   Male     Yes          0      Graduate            No   
496  LP002587   Male     Yes          0  Not Graduate            No   
592  LP002933   Male      No         3+      Graduate           Yes   
66   LP001228   Male      No          0  Not Graduate            No   
127  LP001449   Male      No          0      Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
182             4600                0.0   73.000000             180.0   
379             5391                0.0  130.000000             360.0   
83              6000             2250.0  265.000000             360.0   
452             3948             1733.0  149.000000             360.0   
340             2647             1587.0  173.000000             360.0   
216              150             1800.0  135.000000             360.0   
496             2600             1700.0  107.000000             360.0   
592             9357                0.0  292.000000             360.0   
66              3200             2254.0  126.000000             180.0   
127             3865             1640.0  146.412162             360.0   

     Credit_History Property_Area Loan_Status  TotalIncome  
182             1.0     Semiurban           Y       4600.0  
379             1.0         Urban           Y       5391.0  
83              1.0     Semiurban           N       8250.0  
452             0.0         Rural           N       5681.0  
340             1.0         Rural           N       4234.0  
216             1.0         Rural           N       1950.0  
496             1.0         Rural           Y       4300.0  
592             1.0     Semiurban           Y       9357.0  
66              0.0         Urban           N       5454.0  
127             1.0         Rural           Y       5505.0

In [34]:
loan_data['TotalIncome'].describe()

count      614.000000
mean      7024.705081
std       6458.663872
min       1442.000000
25%       4166.000000
50%       5416.500000
75%       7521.750000
max      81000.000000
Name: TotalIncome, dtype: float64

In [50]:
# Make sure to use labels=False otherwise Interval will be added
loan_data['TotalIncomeGroups'] = pd.cut(loan_data['TotalIncome'], bins=10, include_lowest=True, labels=False)

In [51]:
loan_data['TotalIncomeGroups'].unique()

array([0, 1, 2, 4, 6, 5, 7, 9, 3])

In [52]:
loan_data.sample(10)

Loan_ID  Gender Married Dependents Education Self_Employed  \
568  LP002840  Female      No          0  Graduate            No   
148  LP001519  Female      No          0  Graduate            No   
364  LP002180    Male      No          0  Graduate           Yes   
308  LP001996    Male      No          0  Graduate            No   
52   LP001164  Female      No          0  Graduate            No   
437  LP002401    Male     Yes          0  Graduate            No   
578  LP002877    Male     Yes          1  Graduate            No   
470  LP002515    Male     Yes          1  Graduate           Yes   
516  LP002670  Female     Yes          2  Graduate            No   
233  LP001776  Female      No          0  Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
568             2378                0.0    9.000000             360.0   
148            10000             1666.0  225.000000             360.0   
364             6822                0.0  141.000000             360.0   
308            20233                0.0  480.000000             360.0   
52              4230                0.0  112.000000             360.0   
437             2213             1125.0  146.412162             360.0   
578             1782             2232.0  107.000000             360.0   
470             3450             2079.0  162.000000             360.0   
516             2031             1632.0  113.000000             480.0   
233             8333                0.0  280.000000             360.0   

     Credit_History Property_Area Loan_Status  TotalIncome  TotalIncomeGroups  
568             1.0         Urban           N       2378.0                  0  
148             1.0         Rural           N      11666.0                  1  
364             1.0         Rural           Y       6822.0                  0  
308             1.0         Rural           N      20233.0                  2  
52              1.0     Semiurban           N       4230.0                  0  
437             1.0         Urban           Y       3338.0                  0  
578             1.0         Rural           Y       4014.0                  0  
470             1.0     Semiurban           Y       5529.0                  0  
516             1.0     Semiurban           Y       3663.0                  0  
233             1.0     Semiurban           Y       8333.0                  0

# Splitting traing data

In [53]:
loan_data.shape

(614, 15)

In [54]:
loan_data.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status',
       'TotalIncome', 'TotalIncomeGroups'],
      dtype='object')

In [55]:
loan_data = loan_data[['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 
       'TotalIncome', 'TotalIncomeGroups', 'Loan_Status']]

In [56]:
loan_data.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'TotalIncome',
       'TotalIncomeGroups', 'Loan_Status'],
      dtype='object')

In [57]:
all_ml_columns = loan_data.iloc[:, 1: 14].values
loan_status_column = loan_data.iloc[:, 14].values

In [58]:
all_ml_columns[0]

array(['Male', 'No', '0', 'Graduate', 'No', 5849, 0.0, 146.41216216216216,
       360.0, 1.0, 'Urban', 5849.0, 0], dtype=object)

In [59]:
loan_status_column

array(['Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'N', 'N', 'N', 'Y',
       'Y', 'Y', 'N', 'Y', 'N', 'N', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y',
       'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N',
       'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'N', 'N',
       'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y',
       'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N',
       'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'N', 'N

## Generating Training and Test Dataset

In [60]:
from sklearn.model_selection import train_test_split


In [61]:
X_train, X_test, y_train, y_test = train_test_split(all_ml_columns, loan_status_column, test_size = 1/3, random_state = 0)

In [62]:
X_train

array([['Male', 'Yes', '3+', ..., 'Rural', 5703.0, 0],
       ['Male', 'Yes', '0', ..., 'Rural', 5970.0, 0],
       ['Male', 'Yes', '3+', ..., 'Rural', 4106.0, 0],
       ...,
       ['Male', 'Yes', '3+', ..., 'Semiurban', 8334.0, 0],
       ['Male', 'Yes', '0', ..., 'Urban', 6033.0, 0],
       ['Female', 'Yes', '0', ..., 'Semiurban', 6486.0, 0]], dtype=object)

In [63]:
X_test

array([['Male', 'No', '0', ..., 'Semiurban', 7085.0, 0],
       ['Female', 'No', '0', ..., 'Semiurban', 4230.0, 0],
       ['Male', 'Yes', '0', ..., 'Urban', 10039.0, 1],
       ...,
       ['Male', 'Yes', '0', ..., 'Rural', 3716.0, 0],
       ['Male', 'Yes', '2', ..., 'Urban', 2889.0, 0],
       ['Male', 'Yes', '0', ..., 'Rural', 24996.0, 2]], dtype=object)

In [64]:
y_train

array(['Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N',
       'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N',
       'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'Y', 'N', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y',
       'Y', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'N', 'N', 'N', 'Y', 'N', 'Y',
       'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'N',
       'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N',
       'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'N', 'N',
       'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y

In [65]:
y_test

array(['Y', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N',
       'Y', 'N', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'N', 'N', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'Y',
       'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N',
       'Y', 'Y', 'N', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N',
       'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y

## Logistic Regression (A Quick test to show why you need encoding)

In [66]:
from sklearn.linear_model import LogisticRegression

In [67]:
classifier = LogisticRegression(random_state = 0)

In [68]:
classifier.fit(X_train, y_train)

ValueError: could not convert string to float: 'Male'

## Encoding categorical data and independent vars

In [69]:
X_train[0]

array(['Male', 'Yes', '3+', 'Not Graduate', 'Yes', 5703, 0.0, 130.0,
       360.0, 1.0, 'Rural', 5703.0, 0], dtype=object)

In [70]:
from sklearn.preprocessing import LabelEncoder

In [71]:
labelencoder_X = LabelEncoder()

In [72]:
for i in range(0, 5):
    X_train[:,i] = labelencoder_X.fit_transform(X_train[:,i])

In [73]:
X_train[:,10] = labelencoder_X.fit_transform(X_train[:,10])

In [74]:
X_train[120]

array([1, 1, 2, 0, 0, 3510, 4416.0, 243.0, 360.0, 1.0, 0, 7926.0, 0],
      dtype=object)

In [75]:
X_train

array([[1, 1, 3, ..., 0, 5703.0, 0],
       [1, 1, 0, ..., 0, 5970.0, 0],
       [1, 1, 3, ..., 0, 4106.0, 0],
       ...,
       [1, 1, 3, ..., 1, 8334.0, 0],
       [1, 1, 0, ..., 2, 6033.0, 0],
       [0, 1, 0, ..., 1, 6486.0, 0]], dtype=object)

## Dependent Variable or Y Encoding
### y= f(x)

In [76]:
labelencoder_y = LabelEncoder()

In [77]:
y_train = labelencoder_y.fit_transform(y_train)

In [78]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,

In [79]:
y_train[120]

1

## Test dataset encoding

In [80]:
for i in range(0, 5):
    X_test[:,i] = labelencoder_X.fit_transform(X_test[:,i])
X_test[:,10] = labelencoder_X.fit_transform(X_test[:,10])

In [81]:
y_test = labelencoder_y.fit_transform(y_test)

In [82]:
X_test[100]

array([1, 1, 0, 0, 0, 5923, 2054.0, 211.0, 360.0, 1.0, 0, 7977.0, 0],
      dtype=object)

In [83]:
y_test

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0])

In [84]:
y_test[100]

1

## Re-applying Logistics Regression

In [85]:
lr_classifier = LogisticRegression(random_state = 0)

In [86]:
lr_classifier.fit(X_train, y_train, )

/Users/avkash/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [87]:
# Predicting the Test set results
y_pred_logistic_regression = lr_classifier.predict(X_test)

In [88]:
y_pred_logistic_regression

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0])

## Model Accuracy

In [89]:
from sklearn import metrics

In [90]:
print('Logistic Regression accuracy (%) is: ', metrics.accuracy_score(y_pred_logistic_regression, y_test))

Logistic Regression accuracy (%) is:  0.7951219512195122


## Confusion Matrix

In [91]:
from sklearn.metrics import confusion_matrix

In [92]:
lr_confusion_metrics = confusion_matrix(y_test, y_pred_logistic_regression)

In [93]:
lr_confusion_metrics

array([[ 29,  31],
       [ 11, 134]])

## Using Decision Tree Algorithm

In [94]:
# Fitting Decision Tree Classification to the Training set
from sklearn.tree import DecisionTreeClassifier

In [95]:
dt_classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)

In [96]:
dt_classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [97]:
y_pred_decision_tree = dt_classifier.predict(X_test)

In [98]:
y_pred_decision_tree

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1])

## Decision Tree Accuracy

In [99]:
print('Decision Tree accuracy (%) is: ', metrics.accuracy_score(y_pred_decision_tree, y_test))

Decision Tree accuracy (%) is:  0.7024390243902439


## Confusion Metrics

In [100]:
dt_confusion_metrics = confusion_matrix(y_test, y_pred_decision_tree)

In [101]:
dt_confusion_metrics

array([[ 34,  26],
       [ 35, 110]])

## Improving Decision Tree Accuracy

### Setting max_depth parameters in the decision tree classifier

In [102]:
dt_classifier_improved = DecisionTreeClassifier(criterion = 'entropy', random_state = 0, max_depth=5)

In [103]:
dt_classifier_improved.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=5, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [106]:
y_pred_decision_tree_improved = dt_classifier_improved.predict(X_test)

In [107]:
print('Improved Decision Tree accuracy (%) is: ', metrics.accuracy_score(y_pred_decision_tree_improved, y_test))

Improved Decision Tree accuracy (%) is:  0.8195121951219512


## Prediction Using a custom test data

### Getting a row from X_test dataset (Or Build your own)

In [109]:
X_test

array([1, 1, 0, 0, 0, 5923, 2054.0, 211.0, 360.0, 1.0, 0, 7977.0, 0],
      dtype=object)

In [115]:
sample_data = [[1, 1, 0, 0, 0, 5923, 2054.0, 211.0, 360.0, 1.0, 0, 7977.0, 0]]

In [116]:
import numpy as np

In [117]:
sample_data_item = np.array(sample_data, dtype=object)

In [118]:
sample_data_item

array([[1, 1, 0, 0, 0, 5923, 2054.0, 211.0, 360.0, 1.0, 0, 7977.0, 0]],
      dtype=object)

In [119]:
pred_result = dt_classifier.predict(sample_data_item)

In [120]:
pred_result

array([1])

In [121]:
pred_result[0]

1